### ISSUE TITLE
Week12 lab ready for grading.

### ISSUE THREAD

**Issue by jagreenberg-matc** [madisoncollege-it-programs/python-scripting-jagreenberg-matc#15]

**Comment by cethenmc** [comment]
Chat and filetransfer were worth 4 total each.

The chat is not functioning, and there seems to be some confusion.  I recommend revisiting the slides/videos and utilize the same industry notation we presented.  I especially encourage your looking through the lectures scripts I provided.  Some logic you provided is accurate hence some points (2 points earned)
The filetransfer side has components as well, but you are writing on both sides and reading on the other.  (2 points earned)

You could submit corrections by midnight.  However, your focus should be the final at this point.  If sockets make sense in there, then move over to this afterward.

4 out of 8

**Comment by cethenmc** [comment]
Closing.  Time expired.
