### ISSUE TITLE
Ready for grading, weeks 4 and 5 labs

### ISSUE THREAD

**Issue by jagreenberg-matc** [madisoncollege-it-programs/python-scripting-jagreenberg-matc#3]
Sorry for missing the last few classes, my parents are across the country moving my grandparents into a retirement/assisted living home and I've been filling in and running their business for them while they're gone. Unfortunately, that means I had to be working from morning to night pretty much every day.

I've been keeping up with the slides and readings and I should be back in class tomorrow, thanks for understanding!

I had some trouble with the third part of the week 5 lab. When I ran the len command with the readline function I would get the length of the one line at a time I was getting from readline, and couldn't figure out how to put it together into one big number instead of many smaller numbers.

**Comment by cethenmc** [comment]
Hi, Jack.  Thanks for letting me know.  If you come to class on Thursday, I should be able to help you with week 5 #3.

Week 4 is not executing, are you sure you tested running it from the command line?  
              "usr/bin/env:  bad interpreter:  No such file or directory."

Please fix week 4, so it runs from the command line.
Also, please create a new issue for each assignment, don't have more than one script on a single Issue ticket.

Hopefully, I see you on Thursday, so I can help you with Week 5.

Thanks.

Chris

**Comment by cethenmc** [comment]
FYI - I have temporarily placed 0 in the grade book for each of these two assignments.  You will still receive full credit, as long as your resubmissions are satisfactory.  Thanks!  ~Chris

**Comment by cethenmc** [comment]
looks like you did create a new week 4 and a week 5 entry after this one.
