### ISSUE TITLE
Week 7 lab ready for grading

### ISSUE THREAD

**Issue by jagreenberg-matc** [madisoncollege-it-programs/python-scripting-jagreenberg-matc#8]

**Comment by cethenmc** [comment]
Hi, Jack.  Really nice job here overall.  However, the intention of # 5 is for you two add the two additional servers to the existing/established dictionary that you created in # 1.  This question is separated by # 2 - 4, to drive that point.   **I recorded a 7 of 8 for now, but please either:**
1. resubmit with the correction for # 5 and reply to this Git Hub Issue ticket when it is ready,
2. or reply to this Git Hub Issue ticket and tell me you just want to keep the 7 of 8.

Thanks.

Chris

**Comment by jagreenberg-matc** [comment]
I have resubmitted with #5 done correctly. Thank you.

**Comment by cethenmc** [comment]
Full credit earned.  Closing this Week 7 ticket.
